### PR TITLE
Sorted count distinct

### PR DESCRIPTION
**Pull request by FrancescElies**
Linked to https://github.com/visualfabriq/bquery/issues/10

### CODE REVIEW

**Comment by FrancescElies** [comment]
Continuing https://github.com/visualfabriq/bquery/pull/12

**Comment by CarstVaartjes** [comment]
Hi Francesc, can I merge this / do you want to review this tomorrow?

**Comment by FrancescElies** [comment]
This PR is not finished yet

**Comment by FrancescElies** [comment]
will be merged in https://github.com/visualfabriq/bquery/pull/15

**Pull request closed without merging**
