### PR TITLE
I sorted count distinct v2

### PR DESCRIPTION
**Pull request by FrancescElies**
Issue
```
ct = bq.open(ct_rootdir, mode='r')
barr = ct.where_terms( [('d30106', 'in', [4])] )
ct.groupby( [] , ['a30501'] , bool_arr=barr, agg_method='sorted_count_distinct')
```

### CODE REVIEW

**Comment by CarstVaartjes** [comment]
So the issue is when you do a sorted count distinct without a groupby column?

**Comment by FrancescElies** [comment]
exactly, the problem does not reside within the count distinct itself but with the way the output is formatted, I am making some additional tests at the moment, the problem still has some rough edges, I'll write back once is fully fixed

**Comment by FrancescElies** [comment]
After adding some tests to the suit and doing some manual checks too, I believe this issue is now to be solved

**Comment by FrancescElies** [comment]
Please let me know if I could merge this

**Comment by CarstVaartjes** [comment]
Go ahead, I might make it a bit more "smooth" later on but at least it stop-gaps the issue :)

**Comment by FrancescElies** [comment]
:+1:

**Pull request merged**
