### PR TITLE
Add count mechanisms

### PR DESCRIPTION
**Pull request by FrancescElies**
Implementing https://github.com/visualfabriq/bquery/issues/10

### CODE REVIEW

**Comment by FrancescElies** [comment]
Count in place

**Comment by FrancescElies** [comment]
@CarstVaartjes Count_NA also there

**Comment by FrancescElies** [comment]
@CarstVaartjes up to here works fine, you could merge if you want.
The third one is going to take me longer, therefore I'll do it in a different branch

**Comment by FrancescElies** [comment]
Sorted count distinct: https://github.com/visualfabriq/bquery/pull/13

**Comment by CarstVaartjes** [comment]
Hi Francesc, sorry I'm so late with reviewing. Thing is: I'm not sure if it's smart to do it with if instead of completely separate methods, it's just a gut feeling but think of it doing x million times an if-check where it could be crunching ahead inside it's own, separate function

**Comment by FrancescElies** [comment]
I used inline keyword, since this keyword is a suggestion not a requirement sent to the compiler, to my knowledge, it could happen that the compiler does not perform an inline expansion.
I thought it might make the code a bit more readable, you decide, should the code be copy pasted?

**Comment by FrancescElies** [comment]
Ipython notebook benchmark with same results

**Comment by FrancescElies** [comment]
In my opinion, this is ready to go, but before merging I would suggest testing it against  with real data

**Comment by FrancescElies** [comment]
Tested against random data, ready to merge

**Pull request merged**
