### PR TITLE
Python 3 Fixes

### PR DESCRIPTION
**Pull request by waylonflinn**
Enable use of bquery with Python 3, while maintaining compatibility with 2.7

### CODE REVIEW

**Comment by FrancescElies** [comment]
Hi,
thanks for this PR, though I won't have time until next week to look at it, the only suggestion I would have at the moment would be to modify https://github.com/visualfabriq/bquery/blob/master/.travis.yml#L7 to tell Travis to execute tests for python3 desired version too

**Comment by waylonflinn** [comment]
@FrancescElies thanks for the suggestion. That makes it much easier for everyone to see which test is failing and why.

**Comment by CarstVaartjes** [comment]
@FrancescElies do you know why we're not outputting the results in a sorted order here?

**Comment by FrancescElies** [comment]
Hi guys sorry for my late answer,

the iterable passed to `itertools.groupby` has to be sorted, https://github.com/visualfabriq/bquery/blob/master/bquery/tests/test_ctable.py#L110-L111, that's why `itertools` always return results with alphabetic order. As waylonflinn noted in some tests you'll see `bcolz` results being sorted before comparing them to `itertools` result.

Sorting the test input forces `bcolz` and `itertools` to have the same sorted dataset, so that's  a good workaround. 
I also realised that failing test wasn't very readable, and using dynamic datasets depending on random, maybe not the best idea, both things was not making things easier to debug I guess.
Maybe if we had have a test with a smaller and dataset would have been easier (maybe something like https://github.com/FrancescElies/bquery/blob/master/bquery/tests/test_ctable.py#L671-L699).
If you have any suggestions for future tests, please share

Thanks!

**Pull request merged**
