### PR TITLE
Logo Idea

### PR DESCRIPTION
**Pull request by waylonflinn**
I made a logo to match the ones I made for bccolz and bdot. I'm not satisfied with it yet, but it's a start. This version feels too pixely.

Let me know what you think.

### CODE REVIEW

**Comment by CarstVaartjes** [comment]
Maybe a mirror like "bq" instead? :+1:

**Comment by waylonflinn** [comment]
You're too kind Carst. 😀



I've been meaning to implement your suggestion, just haven't gotten to it yet.





—

**Comment by CarstVaartjes** [comment]
haha, well i thought: let's put some lipstick on the pig to start with and we can always upgrade it later on  ;)

**Comment by waylonflinn** [comment]
:+1:

**Pull request merged**
